# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playerlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlayerList_Dialog(object):
    def setupUi(self, PlayerList_Dialog):
        PlayerList_Dialog.setObjectName("PlayerList_Dialog")
        PlayerList_Dialog.resize(491, 397)
        self.playerList_tableWidget = QtWidgets.QTableWidget(PlayerList_Dialog)
        self.playerList_tableWidget.setGeometry(QtCore.QRect(0, 0, 491, 291))
        self.playerList_tableWidget.setObjectName("playerList_tableWidget")
        self.playerList_tableWidget.setColumnCount(2)
        self.playerList_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.playerList_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.playerList_tableWidget.setHorizontalHeaderItem(1, item)
        self.playerList_tableWidget.horizontalHeader().setDefaultSectionSize(244)
        self.close_pushButton = QtWidgets.QPushButton(PlayerList_Dialog)
        self.close_pushButton.setGeometry(QtCore.QRect(160, 320, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.close_pushButton.setFont(font)
        self.close_pushButton.setObjectName("close_pushButton")

        self.retranslateUi(PlayerList_Dialog)
        QtCore.QMetaObject.connectSlotsByName(PlayerList_Dialog)

    def retranslateUi(self, PlayerList_Dialog):
        _translate = QtCore.QCoreApplication.translate
        PlayerList_Dialog.setWindowTitle(_translate("PlayerList_Dialog", "SpecArt-PlayerList"))
        item = self.playerList_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("PlayerList_Dialog", "地址"))
        item = self.playerList_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("PlayerList_Dialog", "用户名"))
        self.close_pushButton.setText(_translate("PlayerList_Dialog", "返回"))
