# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_Form(object):
    def setupUi(self, login_Form):
        login_Form.setObjectName("login_Form")
        login_Form.resize(290, 147)
        self.label = QtWidgets.QLabel(login_Form)
        self.label.setGeometry(QtCore.QRect(30, 30, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login_Form)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 54, 12))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(login_Form)
        self.lineEdit.setGeometry(QtCore.QRect(78, 26, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(login_Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(78, 56, 181, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(login_Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 100, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(login_Form)
        QtCore.QMetaObject.connectSlotsByName(login_Form)

    def retranslateUi(self, login_Form):
        _translate = QtCore.QCoreApplication.translate
        login_Form.setWindowTitle(_translate("login_Form", "SpecArt-Login"))
        self.label.setText(_translate("login_Form", "Name"))
        self.label_2.setText(_translate("login_Form", "Host"))
        self.pushButton.setText(_translate("login_Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_Form = QtWidgets.QWidget()
    ui = Ui_login_Form()
    ui.setupUi(login_Form)
    login_Form.show()
    sys.exit(app.exec_())
